Added edge option to world decl, that must be present when a dimension is an edge
d409f19/cellmata pull request #115
Opened 2019-05-02 11:12 UTC by NicEastvillage

Resolves #113

2019-05-02 12:12 UTC, falkecarlsen requested changes
Looks fine. Just one thing that seems wrong. Please do try an pretty print to see if it works well. Use `large-program.cell` maybe.

2019-05-02 12:12 UTC, cogitantium commented on compiler/src/main/kotlin/visitors/prettyprinter.kt
> +                    "[edge$separator"
```suggestion
                    "[edge]$separator"
```

Missing a closing square bracket

2019-05-03 18:40 UTC, NicEastvillage commented on compiler/src/main/kotlin/visitors/prettyprinter.kt
> +                    "[edge$separator"
Fixed in 958249b

2019-05-03 18:45 UTC, NicEastvillage commented
@cogitantium this is the pretty print result now. The for-loop still has an extra semicolon, and the indentation is weird, but otherwise everything is good.
```
world {
	size = 1000 [edge], 1000 [wrap];
	edge = alive1;
	tickrate = 100;
	cellsize = 5;
}

const boolean = false;

const integer = 42;

const floating = 42.42;

const goodProgram = true;

neighbourhood foobar {
	(-1, 1), (0, 1), (1, 1), (-1, 0), (1, 0)
}

state alive1 (0, 0, 0) {
	let a = -foo(42);
	become alive2;
}

state alive2 (0, 0, 0) {
	let a = -foo(42);
	become alive3;
}

state alive3 (0, 0, 0) {
	let a = -foo(42);
	become alive4;
}

state alive4 (0, 0, 0) {
	let a = -foo(42);
	become alive5;
}

state alive5 (0, 0, 0) {
	let a = -foo(42);
	let x = 0;
	for (	 x = 5;
x >= a;	 x = x + 1;
) {
	if (x != 0) {
		 x = -5;
break;
	} else {
		 x = 42 + 3 / 176 * 22;
continue;
	}
}
	become alive6;
}

state alive6 (0, 0, 0) {
	let a = -foo(42);
	let b = bar(a, true);
	if (b != -16) {
		become alive5;
	}
	become alive1;
}

function foo(int x) int {
	return x + 42;
}

function bar(int x, bool y) int {
	if (y) {
		return x + 42;
	} elif (!y) {
		return x;
	} else {
		return x + 4;
	}
}
```

2019-05-06 08:58 UTC, falkecarlsen approved these changes

2019-05-06 08:59 UTC, merged