Added commandline argument parsing
d409f19/cellmata pull request #151
Opened 2019-05-09 08:45 UTC by jenrik

2019-05-09 14:05 UTC, NicEastvillage requested changes

2019-05-09 14:05 UTC, NicEastvillage commented on compiler/src/main/kotlin/main.kt
> +    ).default("silent").addValidator {
Let's define each level at some point. Default should not be "silent" as the typical user should know what compile errors and warnings the compiler found.

2019-05-09 14:05 UTC, NicEastvillage commented on compiler/src/main/kotlin/main.kt
> +                    output = Paths.get(outputDir)
What about log level and graph phases?

2019-05-09 14:05 UTC, NicEastvillage commented on compiler/src/main/kotlin/main.kt
> +        ErrorLogger.printAllWarnings(if (settings.logLevel == LogLevel.DEBUG) Files.lines(settings.source) else null)
Ideally we want to print warnings if the log level is minimal *or greater*.

2019-05-10 07:09 UTC, NicEastvillage commented on compiler/src/main/kotlin/main.kt
> +    ).default("silent").addValidator {
Log levels:
- Silent: Nothing except exit code
- Minimal: Errors and warnings without pointers
- Debug: Errors and warnings with pointers
- verbose: Errors and warnings with pointers plus whatever else we got

2019-05-10 12:28 UTC, jenrik commented on compiler/src/main/kotlin/main.kt
> +    ).default("silent").addValidator {
I agree that we should probably move the default log level to minimal.

My suggestions for levels:

* Silent: Nothing except exit code
* Minimal: Error intended for the user, i.e. syntax and semantic error, and warnings
* Debug: Debugging information intended for compiler developers, i.e. phase startet, and other internal information.
* Verbose: **Everything**, entering and leaving visitor functions, caught exceptions, ...

2019-05-10 12:30 UTC, jenrik commented on compiler/src/main/kotlin/main.kt
> +                    output = Paths.get(outputDir)
Thats a bug

2019-05-10 12:59 UTC, NicEastvillage commented on compiler/src/main/kotlin/main.kt
> +                    output = Paths.get(outputDir)
Added these myself in e175f6d

2019-05-10 12:59 UTC, NicEastvillage commented on compiler/src/main/kotlin/main.kt
> +        ErrorLogger.printAllWarnings(if (settings.logLevel == LogLevel.DEBUG) Files.lines(settings.source) else null)
Added this myself in e175f6d

2019-05-10 12:59 UTC, NicEastvillage commented on compiler/src/main/kotlin/main.kt
> +    ).default("silent").addValidator {
Sure!

2019-05-10 12:59 UTC, NicEastvillage approved these changes

2019-05-13 06:47 UTC, merged