Codegen multistate
d409f19/cellmata pull request #159
Opened 2019-05-13 07:43 UTC by jenrik

Adds support for multistates in the Kotlin code generator. Also fixes functions not having any arguments, and several unreachable visitor functions having a TODO statement instead of a proper error.

2019-05-13 08:31 UTC, NicEastvillage requested changes

2019-05-13 08:31 UTC, NicEastvillage commented on compiler/src/main/kotlin/visitors/codegen.kt
> +            ${INDENT}throw Error()
Maybe use OutOfBoundsException?

2019-05-13 08:31 UTC, NicEastvillage commented on compiler/src/main/kotlin/visitors/codegen.kt
> +                $INDENT$INDENT$INDENT${INDENT}throw Error()
Maybe use OutOfBoundsException?

2019-05-13 08:31 UTC, NicEastvillage commented on compiler/src/main/kotlin/visitors/codegen.kt
> +                builder.append(", ")
Are you sure you got a comma between worldView and first argument?

2019-05-13 08:42 UTC, NicEastvillage commented
Your PR does not resolve #157 because FuncCall is now broken for built-in functions

2019-05-14 11:12 UTC, jenrik commented
Builtins have been updated to reflect the changes to the function argument convention

2019-05-14 17:53 UTC, NicEastvillage approved these changes
Nice

2019-05-15 13:02 UTC, merged