Added support for floats in grammar
d409f19/cellmata pull request #17
Opened 2019-03-14 13:48 UTC by cogitantium

- Adds support for floats by expanding literal productions.
- Fixes usage of `integer_literal` rule in other productions, instead of using `DIGITS` token.

Resolves #7.

2019-03-14 14:58 UTC, NicEastvillage requested changes
Array subscription can also be an expression. E.g. `arr[x + 1]`

Otherwise, good!

2019-03-14 14:58 UTC, NicEastvillage commented on compiler/src/main/antlr/Cellmata.g4
> +    | expr_10 SQ_BRACKET_START integer_literal SQ_BRACKET_END # arrayLookupExpr
```suggestion
    | expr_10 SQ_BRACKET_START expr SQ_BRACKET_END # arrayLookupExpr
```

2019-03-14 14:58 UTC, NicEastvillage commented on compiler/src/main/antlr/Cellmata.g4
> +array_lookup: var_ident SQ_BRACKET_START integer_literal SQ_BRACKET_END ;
```suggestion
array_lookup: var_ident SQ_BRACKET_START expr SQ_BRACKET_END ;
```

2019-03-14 15:09 UTC, jenrik approved these changes

2019-03-15 08:28 UTC, NicEastvillage approved these changes

2019-03-15 08:29 UTC, merged