removed pre- and post increment/decrement
d409f19/cellmata pull request #59
Opened 2019-03-27 12:10 UTC by MathiasMehl

Removed pre- and post increment/decrement from both grammar and compiler files. 
Removed all increments/decrements in stress.cell, and renamed variables
Resolves issue #52

2019-03-27 12:22 UTC, NicEastvillage requested changes
I see that the grammar rule `modifiable_ident` is no longer used. Let's remove that too. Otherwise good job!

2019-03-27 13:16 UTC, NicEastvillage submitted a review, later dismissed

2019-03-28 08:35 UTC, falkecarlsen submitted a review, later dismissed

2019-03-28 08:49 UTC, falkecarlsen approved these changes

2019-03-28 08:50 UTC, merged