Updated cgol script, and added a version without built-in functions
d409f19/cellmata pull request #68
Opened 2019-04-09 07:17 UTC by NicEastvillage

Made an updated version of Game of Life. Also added a version without the built-in function `count`, but a user defined version instead.

2019-04-09 18:29 UTC, falkecarlsen requested changes
Nice. Seems like CGOL sans builtin-functions is faulty though, also minor formatting comments.

2019-04-09 18:29 UTC, cogitantium commented on dreamcode/v3/cgol.cell
> +// The logic is applied to each cell with this state.
```suggestion
// The logic is applied to each cell with this state at each tick.
```
I think it's worth mentioning that this happens at each update cycle/tick

2019-04-09 18:29 UTC, cogitantium commented on dreamcode/v3/cgol-without-builtin-functions.cell
> +		counter = counter + 1;
What does this actually count? Right now it just counts counter up to eight through the for-loop.

Neither `nei` or `z` are used, too.

2019-04-09 18:29 UTC, cogitantium commented on dreamcode/v3/cgol-without-builtin-functions.cell
> +	// The count function returns how many states in neighbourhood is of a given state.
One indentation too much, it seems.

2019-04-09 19:48 UTC, jenrik reviewed
I have no comments besides what @cogitantium has already mentioned

2019-04-10 07:47 UTC, falkecarlsen approved these changes

2019-04-10 07:51 UTC, merged