Made jar executeable and program should now be given as argument
d409f19/cellmata pull request #81
Opened 2019-04-13 14:15 UTC by NicEastvillage

Added a run task to gradle, so we can run the compiler from gradle.

Also made the jar task produce a fat and executeable jar.

The .cell file which should be compiled should now be given as an argument. I.e. the compiled program is not hardcoded anymore. So if you want to run the compiler to compile `stress.cell` you should now either do
**1) use java**
run `gradlew jar`
followed by `java -jar build/libs/cellumata-1.0-SNAPSHOT.jar src/main/resources/stress.cell`

**2) use gradle**
run `gradlew run -PappArgs="['src/main/resources/stress.cell']"`

**3) configure intellij's run**
Setup intellij to run `gradlew run` and use the argument `-PappArgs="['src/main/resources/stress.cell']"`
![billede](https://user-images.githubusercontent.com/21122471/56080901-2466a700-5e07-11e9-93ad-031398c7c09c.png)

We currently don't have other options for arguments, but I made them easy to add.

2019-04-15 09:50 UTC, jenrik requested changes

2019-04-15 09:50 UTC, jenrik commented on compiler/build.gradle
> +    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
Doesn't gradle have builtin functions to handle the collections for classes?

2019-04-15 10:24 UTC, NicEastvillage commented on compiler/build.gradle
> +    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
This is what stack overflow told me to do.

2019-04-24 20:51 UTC, jenrik approved these changes

2019-04-26 10:31 UTC, merged